import type { Metadata } from "next";
import { Inconsolata } from 'next/font/google'
import "./globals.css";

const inconsolata = Inconsolata({subsets: ['latin']})

export const metadata: Metadata = {
  title: "Drive",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inconsolata.className} antialiased bg-da`}
      >
        {children}
      </body>
    </html>
  );
}
