import type { Metadata } from "next";
import { Poppins } from 'next/font/google'
import "./globals.css";
import 'react-circular-progressbar/dist/styles.css';

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
  variable: '--font-poppins',
})

export const metadata: Metadata = {
  title: "Drive",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.className} antialiased bg-da`}
      >
        {children}
      </body>
    </html>
  );
}
